config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :category, presence: true, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :restaurant, presence: true
  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: [0, 1, 2, 3, 4, 5] }, numericality: { only_integer: true}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurants = Restaurant.find(params[:id])
  end

  def new
    @restaurants = Restaurant.new
  end

  def create
    @restaurants = Restaurant.new(restaurants_params)
    @restaurants.save
    redirect_to restaurant_path(@restaurants)
  end

  def edit
    @restaurants = Restaurant.find(params[:id])
  end

  def update
    @restaurants = Restaurant.find(params[:id])
    @restaurants.update(restaurants_params)
    redirect_to restaurant_path(@restaurants)
  end

  def destroy
    @restaurants = Restaurant.find(params[:id])
    @restaurants.destroy
    redirect_to restaurants_path
  end

  private

  def restaurants_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category, :review)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @review = Review.new
    @restaurants = Restaurant.find(params[:restaurant_id])
  end

  def create
    @restaurants = Restaurant.find(params[:restaurant_id])
    @review = Review.new(reviews_params)
    @review.restaurant = @restaurants
    @review.save
    redirect_to restaurant_path(@review.restaurant)
  end

  private

  def reviews_params
    params.require(:review).permit(:content, :rating, :restaurant)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/edit.html.erb
<h1>Edit a restaurant</h1>

<%= form_for(@restaurants) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :address %>
  <%= f.text_field :address %>

  <%= f.label :phone_number %>
  <%= f.text_field :phone_number %>

  <%= f.label :category %>
  <%= f.select :category, ["chinese", "italian", "japanese", "french", "belgian"]%>

  <%= f.submit %>
<% end %>

app/views/restaurants/index.html.erb
<h1>All restaurants:</h1>
<% @restaurants.each do |restaurant| %>
<div class="tasks-ordered">
  <h2><%= link_to restaurant.name, restaurant_path(restaurant) %></h2>
</div>
<% end %>

<h2><%= link_to "Add a new restaurant", new_restaurant_path %></h2>

app/views/restaurants/new.html.erb
<h1>Create a new restaurant</h1>

<%= form_for(@restaurants) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :address %>
  <%= f.text_field :address %>

  <%= f.label :phone_number %>
  <%= f.text_field :phone_number %>

  <%= f.label :category %>
  <%= f.select :category, ["chinese", "italian", "japanese", "french", "belgian"]%>

  <%= f.submit %>
<% end %>

app/views/restaurants/show.html.erb
<h1>Details of the restaurant:</h1>
<div class="ordered">
  <h3> <%= @restaurants.name %> </h3>
  <p>Address: <%= @restaurants.address %> </p>
  <p>Category: <%= @restaurants.category %> </p>
  <p>Phone number: <%= @restaurants.phone_number %> </p>
</div>

<div class="review-ordered">
  <% @restaurants.reviews.each do |rev| %>
  <div class="tasks-ordered">
    <p> <span style="font-weight: bold;">Rate of <%=rev.rating%> :</span> <%= rev.content %></p>
  </div>
  <% end %>
</div>
<p>
  <%= link_to "Back to all restaurants", restaurants_path %>
  <br>
  <%= link_to "Destroy \"#{@restaurants.name}\"", restaurant_path(@restaurants), method: :delete, data: { confirm: "Are you sure?"} %>
  <br>
  <%= link_to "Edit the restaurant", edit_restaurant_path(@restaurants) %>
  <br>
  <%= link_to "Add a review", new_restaurant_review_path(@restaurants) %>
</p>

app/views/reviews/new.html.erb
<h1>Create a new review</h1>

<%= form_for([@restaurants, @review]) do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content %>

  <%= f.label :rating %>
  <%= f.number_field :rating %>

  <%= f.submit %>
<% end %>